tokens as inputs

diff --git a/.github/actions/docker-build/action.yml b/.github/actions/docker-build/action.yml
--- a/.github/actions/docker-build/action.yml
+++ b/.github/actions/docker-build/action.yml
@@ -3,9 +3,23 @@ description: 'Greet someone'
 
 inputs:
   test:  # id of input
-    description: 'Who to greet'
+    description: 'Should we test the image?'
+    required: false
+    default: 'false'
+  token:
+    description: 'GitHub token'
     required: true
-    default: 'World'
+  repository_owner:
+    description: 'Owner of the repository'
+    required: true
+  repository_name:
+    description: 'Name of the repository'
+    required: true
+  version:
+    description: 'Version of the image'
+    required: false
+
+
 
 outputs:
   tags:
@@ -20,6 +34,14 @@ runs:
   using: "composite"
   steps:
 
+    - name: fail if no token
+      shell: bash
+      run: |
+        if [ -z "${{ inputs.token }}" ]; then
+          echo "Token is required"
+          exit 1
+        fi
+
     - name: Set up QEMU
       uses: docker/setup-qemu-action@v3
 
@@ -30,8 +52,8 @@ runs:
       uses: docker/login-action@v3
       with:
         registry: ghcr.io
-        username: ${{ github.repository_owner }}
-        password: ${{ secrets.GITHUB_TOKEN }}
+        username: ${{ inputs.repository_owner }}
+        password: ${{ inputs.token }}
 
     - name: Docker meta
       id: docker_meta
@@ -42,7 +64,7 @@ runs:
         #  1. add the fully qualified image name to the list
         #  2. insert another login action above for the registry
         images: |
-          ghcr.io/${{github.repository_owner}}/${{github.event.repository.name}}
+          ghcr.io/${{ inputs.repository_owner }}/${{ inputs.repository_name }}
 
         # generate Docker tags based on the following events/attributes.
         # It ends up instructing further actions to tag the image with the git sha, semver, and latest.
@@ -59,9 +81,9 @@ runs:
           type=ref,event=branch
           type=sha,enable=true,priority=100,prefix=gitsha-,suffix=,format=short
           type=raw,value=latest,enable={{is_default_branch}}
-          type=pep440,pattern={{version}},value=${{ steps.Process.outputs.tag_name }}
-          type=pep440,pattern={{major}}.{{minor}},value=${{ steps.Process.outputs.tag_name }}
-          type=pep440,pattern={{major}},value=${{ steps.Process.outputs.tag_name }}
+          type=pep440,pattern={{version}},value=${{ inputs.version }}
+          type=pep440,pattern={{major}}.{{minor}},value=${{ inputs.version }}
+          type=pep440,pattern={{major}},value=${{ inputs.version }}
 
     - name: Build and push
       uses: docker/build-push-action@v5
@@ -69,13 +91,13 @@ runs:
       with:
         context: .
         load: true
-        tags: ${{github.event.repository.name}}_TEST
+        tags: ${{ inputs.repository_name }}_TEST
 
     - name: Test
       shell: bash
       if: ${{ inputs.test == 'true' }}
       run: |
-        docker run --rm ${{github.event.repository.name}}_TEST
+        docker run --rm ${{ inputs.repository_name }}_TEST
 
     - name: Build and push
       uses: docker/build-push-action@v5
@@ -84,7 +106,7 @@ runs:
         push: true
         tags: ${{ steps.docker_meta.outputs.tags }}
         labels: ${{ steps.docker_meta.outputs.labels }}
-        cache-from: type=registry,ref=user/app:latest
+        cache-from: type=registry,ref=ghcr.io/${{ inputs.repository_owner }}/${{ inputs.repository_name }}:latest
         cache-to: type=inline
 
     - name: Cleanup
